apiVersion: v1
data:
  allenvs: |+
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=
    APP_DEBUG=true
    APP_URL=http://localhost

    LOG_CHANNEL=daily
    LOG_LEVEL=debug

    DB_CONNECTION=mysql
    DB_HOST=dbsvc
    DB_PORT=3306
    DB_DATABASE=ecare
    DB_USERNAME=ecare
    
    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    MEMCACHED_HOST=127.0.0.1

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_MAILER=smtp
    MAIL_HOST=mailhog
    MAIL_PORT=1025
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS=null
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

    FAST_SMS_KEY = "$2y$10$DNZCfxNNp5U57oKEO3Ze1.j57WrFZj1XiW5y4C4dfkpXV6H17DplG28"

    ALGOLIA_APP_ID=UFPO9OW7XY
    ALGOLIA_SECRET=ce1e425ed3526fdf94baf7694a0a8b5b

    JWT_SECRET=5Nu9GRRKTR5z75jDZUoTDoSOoHh2cjn7ZWIZtE5zDcv6G9mDM8t26ow8RtfgKNUw


kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecare-prod

