apiVersion: v1
kind: LimitRange
metadata: 
  name: firstlimit
spec:
  limits:
    - 
      default: 
        cpu: 0.5
        memory: 500Mi
      defaultRequest: 
        cpu: 0.2
        memory: 200Mi
      type: Container
  
