apiVersion: v1
kind: ReplicationController 
metadata: 
  name: firstrc 
spec:
  replicas: 3 
  selector: 
    app: test 
  template: 
    metadata: 
      name: firstpod 
      labels: 
        app: test 
    spec:  
      containers: 
        - 
          name: nginx 
          image: nginx:alpine

