apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: firstrs
spec:
  replicas: 3 
  selector: 
    matchExpressions: 
      - 
        key: app
        operator: In
        values: 
          - myapp1 
          - myapp2 
      - 
        key: type 
        operator: NotIn 
        values: 
          - frontend

  template: 
    metadata: 
      name: firstrs|pod
      labels: 
        app: myapp1 
        app: myapp2 
        type: backend 
    spec:  
      containers: 
        - 
          name: nginx 
          image: nginx:alpine

